# Default values for shelter-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: shelter-app
general:
  mysql_root_pass: "123456"
  mysql_db_name: "nenos_academy"
  mysql_username: "my_user"
  mysql_password: "my_password"

mongo:
  replicaCount: 1

  image:
    repository: mongo
    pullPolicy: Never
    tag: "6.0"

  podLabels:
    app: mongodb


  service:
    type: ClusterIP
    port: 27017

  resources:
    requests:
      memory: "128Mi" # Minimum memory required
      cpu: "250m"     # Minimum CPU required
    limits:
      memory: "512Mi" # Maximum memory allowed
      cpu: "500m"

  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  autoscaling:
    enabled: false
    # minReplicas: 1
    # maxReplicas: 10
    # targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  storage:
    size: 1Gi

  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: shelter-app-mongo

sql:
  replicaCount: 1

  image:
    repository: mysql
    pullPolicy: Never
    tag: "8.0"

  podLabels:
    app: mysql

  service:
    type: ClusterIP
    port: 3306

  resources:
    requests:
      memory: "128Mi" # Minimum memory required
      cpu: "250m"     # Minimum CPU required
    limits:
      memory: "512Mi" # Maximum memory allowed
      cpu: "500m"

  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  autoscaling:
    enabled: false
    # minReplicas: 1
    # maxReplicas: 10
    # targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  storage:
    size: 1Gi

  volumes:
  - name: sqldb-data
    persistentVolumeClaim:
      claimName: shelter-app-sql

api:
  replicaCount: 1

  image:
    repository: nenos-academy-shelter-app
    pullPolicy: Never
    tag: latest

  podLabels:
    app: api

  service:
    type: ClusterIP
    port: 8080

  resources:
    requests:
      memory: "128Mi" # Minimum memory required
      cpu: "250m"     # Minimum CPU required
    limits:
      memory: "512Mi" # Maximum memory allowed
      cpu: "500m"

  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  autoscaling:
    enabled: false
    # minReplicas: 1
    # maxReplicas: 10
    # targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

web:
  replicaCount: 1

  image:
    repository: nenos-academy-shelter-app
    pullPolicy: Never
    tag: latest

  podLabels:
    app: web

  service:
    type: ClusterIP
    port: 8050

  resources:
    requests:
      memory: "128Mi" # Minimum memory required
      cpu: "250m"     # Minimum CPU required
    limits:
      memory: "512Mi" # Maximum memory allowed
      cpu: "500m"

  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  ingress:
    enabled: false

  autoscaling:
    enabled: false
    # minReplicas: 1
    # maxReplicas: 10
    # targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80