version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongodb_data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: 123456

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nenos_academy
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
      mysql:
        condition: service_healthy
    container_name: shelter-api
    environment:
      SQL_USER: root
      SQL_PASSWORD: 123456
    command: ["python3", "/app/src/api/main.py"]

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      api:
        condition: service_started
    container_name: shelter-web
    environment:
      SQL_USER: root
      SQL_PASSWORD: 123456
    command: ["python3", "/app/src/web/main.py"]

  

volumes:
  mongodb_data:
  mysql_data:
