apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shelter-app.fullname" . }}-sql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sql.storage.size }}