apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shelter-app.fullname" . }}-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.storage.size }}