apiVersion: v1
kind: Service
metadata:
  name: {{ include "shelter-app.fullname" . }}-web
  labels:
    {{- include "shelter-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.web.podLabels | nindent 4 }}
