apiVersion: v1
kind: Service
metadata:
  name: {{ include "shelter-app.fullname" . }}-mongo
  labels:
    {{- include "shelter-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.mongo.podLabels | nindent 4 }}
