name: CI/CD Pipeline

# when to execute a pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    # image used to run the pipeline
    runs-on: ubuntu-latest

    steps:
      # downloads the code onto the machine of the pipeline
      - name: Checkout code
        uses: actions/checkout@v3

      # installs docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # builds the docker image
      - name: Build Docker image
        run: docker build -t shelter-app .

      - name: Run linting with pylint
        run: docker run --rm shelter-app pylint /app/src

      - name: Run tests with pytest
        run: docker run --rm shelter-app pytest /app/test